import { useMemo, useState } from 'react';
import { compileView } from '../../../../standalone/view-compiler.mjs';
import { applyOperations } from '../../../../standalone/design-model.mjs';
import { DesignEditor } from './DesignEditor.jsx';
import { CopyButton, DiffSummary, Empty, Field, Operations, STATUS_LABELS, Tag, lines, shortId } from './Shared.jsx';

export function DesignWorkspace({ workspace, session, candidate, selectSession, selectCandidate, command, busy, selectedId, prepare, converse, model, response, clearResponse, pending, applyPending, discardPending }) {
  const [creatingSession, setCreatingSession] = useState(false);
  const [creatingCandidate, setCreatingCandidate] = useState(false);
  const [decisionReason, setDecisionReason] = useState('');
  const candidates = session ? workspace.candidates.filter((item) => item.sessionId === session.id) : [];
  const stale = candidate && candidate.baseSnapshotId !== workspace.current.snapshot.id;
  return <div className="st-design-layout">
    <aside className="st-design-nav"><div className="st-inspector-heading"><p className="st-eyebrow">设计上下文</p><h2>设计会话</h2></div><button type="button" className="secondary-button" onClick={() => setCreatingSession((value) => !value)}>新建设计会话</button>
      <div className="st-session-list">{workspace.sessions.map((item) => <button type="button" key={item.id} className={item.id === session?.id ? 'selected' : ''} onClick={() => { selectSession(item.id); clearResponse(); }}><strong>{item.title}</strong><small>{item.kind} · {workspace.candidates.filter((value) => value.sessionId === item.id).length} 份方案</small></button>)}</div>
      <p className="st-note">需求、方案、评审与取舍保存在项目工作区。图谱之外的文本方案同样可以参与比较。</p>
    </aside>
    <main className="st-design-main"><div className="st-workspace-title"><div><p className="st-eyebrow">形成目标与决策</p><h1>设计与评审</h1></div><Tag>{model.available ? model.label : '外部分析交接'}</Tag></div>
      {creatingSession ? <SessionForm busy={busy} onSubmit={async (input) => { const result = await command('create-session', input); if (result) { const created = result.workspace.sessions.at(-1); selectSession(created.id); setCreatingSession(false); } }} onCancel={() => setCreatingSession(false)} /> : null}
      {!session ? <Empty title="从一个设计问题开始">创建会话，写下需求或架构问题，再比较候选方案。可以从需求澄清、模块调整、技术选型或框架迁移评估开始。</Empty> : <>
        <details className="st-session-details"><summary>{session.title} · 问题与约束</summary><SessionForm key={session.id} initial={session} busy={busy} onSubmit={(input) => command('update-session', { id: session.id, title: input.title, question: input.question, constraints: input.constraints, unknowns: input.unknowns })} /></details>
        <section className="st-candidates"><div className="st-section-heading"><h2>候选方案</h2><button type="button" className="secondary-button" disabled={busy} onClick={() => setCreatingCandidate((value) => !value)}>新增候选方案</button></div>
          {creatingCandidate ? <CandidateForm busy={busy} onCancel={() => setCreatingCandidate(false)} onSubmit={async (input) => { const result = await command('create-candidate', { sessionId: session.id, ...input }); if (result) { selectCandidate(result.workspace.candidates.at(-1).id); setCreatingCandidate(false); } }} /> : null}
          {!candidates.length ? <p className="st-note">创建候选后，可以自然语言讨论、图上调整或导入外部评审。新候选以当前源码为基线。</p> : <div className="st-candidate-grid">{candidates.map((item) => <button type="button" key={item.id} className={`st-candidate-card ${item.id === candidate?.id ? 'selected' : ''}`} onClick={() => { selectCandidate(item.id); clearResponse(); }}><div><strong>{item.title}</strong><Tag tone={item.baseSnapshotId !== workspace.current.snapshot.id ? 'attention' : 'target'}>{item.baseSnapshotId !== workspace.current.snapshot.id ? '基线过期' : `v${item.version}`}</Tag></div><p>{item.description || '尚无文本说明'}</p><DiffSummary base={item.baseModel} target={item.target} />{session.selectedCandidateId === item.id ? <small>已选方案 · {session.decisionReason}</small> : <small>候选方案</small>}</button>)}</div>}
        </section>
        {!candidate ? <Conversation key={session.id} session={session} candidate={null} model={model} busy={busy} converse={converse} response={response} prepare={prepare} stale={false} /> : null}
        {candidate ? <>
          <div className="st-candidate-toolbar"><strong>当前编辑：{candidate.title}</strong><button type="button" className="secondary-button" disabled={busy || stale || !(candidate.historyIndex > 0)} onClick={() => command('undo', { candidateId: candidate.id })}>撤销</button><button type="button" className="secondary-button" disabled={busy || stale || candidate.historyIndex >= candidate.history.length - 1} onClick={() => command('redo', { candidateId: candidate.id })}>重做</button><button type="button" className="secondary-button" disabled={busy} onClick={() => command('save-candidate', { candidateId: candidate.id })}>保存方案</button><span className="st-note">{candidate.savedAt ? `上次保存：${new Date(candidate.savedAt).toLocaleString()}` : '尚未标记保存'}</span></div>
          <details><summary>编辑候选文本说明</summary><CandidateTextForm key={`${candidate.id}:${candidate.version}`} candidate={candidate} command={command} disabled={busy || stale} /></details>
          {stale ? <div className="st-warning" role="status">源码已刷新，此候选基线过期。可以查看、导出历史说明与回读；继续设计请从当前源码新建候选。</div> : null}
          {candidate.unknowns?.length ? <div className="st-warning"><strong>设计待确认项</strong><ul>{candidate.unknowns.map((item, index) => <li key={index}>{typeof item === 'string' ? item : JSON.stringify(item)}</li>)}</ul></div> : null}
          <Conversation key={session.id} session={session} candidate={candidate} model={model} busy={busy} converse={converse} response={response} prepare={prepare} stale={stale} />
          {pending ? <ProposalPanel pending={pending} candidate={candidate} currentSnapshotId={workspace.current.snapshot.id} busy={busy} apply={applyPending} discard={discardPending} /> : null}
          <DesignEditor candidate={candidate} selectedId={selectedId} prepare={prepare} disabled={busy || stale} />
          <details className="st-advanced"><summary>导入外部结构化建议</summary><OperationImport prepare={prepare} disabled={busy || stale} /></details>
          <section className="st-decision"><h3>记录方案选择</h3><Field label="选择当前候选的理由"><textarea rows="2" placeholder="相较于其他方案，为什么采纳这一份？还有什么问题？" value={decisionReason} onChange={(event) => setDecisionReason(event.target.value)} /></Field><button type="button" className="primary-button" disabled={busy || stale || !decisionReason.trim()} onClick={async () => { const result = await command('select-candidate', { sessionId: session.id, candidateId: candidate.id, reason: decisionReason }); if (result) setDecisionReason(''); }}>选定此方案并记录理由</button><p className="st-note">选定方案表示设计决策，当前源码仍由后续读取确定。</p></section>
          <ReviewPanel key={candidate.id} candidate={candidate} reviews={workspace.reviews.filter((review) => review.candidateId === candidate.id)} currentSnapshotId={workspace.current.snapshot.id} command={command} busy={busy} />
        </> : null}
      </>}
    </main>
  </div>;
}

function SessionForm({ initial, onSubmit, onCancel, busy }) {
  const [title, setTitle] = useState(initial?.title || ''); const [kind, setKind] = useState(initial?.kind || 'architecture');
  const [question, setQuestion] = useState(initial?.question || ''); const [constraints, setConstraints] = useState(Array.isArray(initial?.constraints) ? initial.constraints.join('\n') : initial?.constraints || ''); const [unknowns, setUnknowns] = useState((initial?.unknowns || []).join('\n'));
  return <form className="st-form" onSubmit={(event) => { event.preventDefault(); void onSubmit({ title, kind, question, constraints, unknowns: lines(unknowns) }); }}><div className="st-form-grid"><Field label="会话名称"><input required value={title} onChange={(event) => setTitle(event.target.value)} /></Field><Field label="设计问题类型"><select value={kind} disabled={Boolean(initial)} onChange={(event) => setKind(event.target.value)}><option value="architecture">架构与模块调整</option><option value="requirements">需求分析</option><option value="technology">技术选型</option><option value="migration">框架迁移评估</option></select></Field></div><Field label="问题与使用场景"><textarea required rows="3" value={question} onChange={(event) => setQuestion(event.target.value)} /></Field><Field label="约束与验收条件"><textarea rows="2" value={constraints} onChange={(event) => setConstraints(event.target.value)} /></Field><Field label="待确认问题（每行一项）"><textarea rows="2" value={unknowns} onChange={(event) => setUnknowns(event.target.value)} /></Field><div className="st-form-actions"><button type="submit" className="primary-button" disabled={busy}>{initial ? '保存问题与约束' : '创建设计会话'}</button>{onCancel ? <button type="button" className="secondary-button" onClick={onCancel}>取消</button> : null}</div></form>;
}

function CandidateForm({ onSubmit, onCancel, busy }) {
  const [title, setTitle] = useState(''); const [description, setDescription] = useState('');
  return <form className="st-form" onSubmit={(event) => { event.preventDefault(); void onSubmit({ title, description }); }}><Field label="候选方案名称"><input required placeholder="例如：渐进拆分通知服务" value={title} onChange={(event) => setTitle(event.target.value)} /></Field><Field label="方案说明、收益与代价"><textarea rows="3" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="文本候选可以先讨论目标和取舍，暂不改变图谱。" /></Field><div className="st-form-actions"><button type="submit" disabled={busy} className="primary-button">创建候选方案</button><button type="button" className="secondary-button" onClick={onCancel}>取消</button></div></form>;
}

function CandidateTextForm({ candidate, command, disabled }) {
  const [title, setTitle] = useState(candidate.title); const [description, setDescription] = useState(candidate.description);
  return <form className="st-form" onSubmit={(event) => { event.preventDefault(); void command('update-candidate', { candidateId: candidate.id, candidateVersion: candidate.version, baseSnapshotId: candidate.baseSnapshotId, title, description }); }}><Field label="编辑候选名称"><input required value={title} onChange={(event) => setTitle(event.target.value)} /></Field><Field label="编辑候选说明与取舍"><textarea rows="4" value={description} onChange={(event) => setDescription(event.target.value)} /></Field><p className="st-note">保存文本变更会增加候选版本，先前评审需要重新确认。</p><button type="submit" className="secondary-button" disabled={disabled}>保存文本方案</button></form>;
}

function Conversation({ session, candidate, model, busy, converse, response, prepare, stale }) {
  const [message, setMessage] = useState('');
  return <section className="st-conversation"><div className="st-section-heading"><h3>自然语言讨论</h3><span>{model.available ? model.label : '未配置模型，可生成外部分析说明'}</span></div>
    {session.messages.length ? <div className="st-messages" aria-label="设计对话记录">{session.messages.map((item, index) => <article key={item.id || index} className={item.role === 'user' ? 'user' : 'assistant'}><strong>{item.role === 'user' ? '你' : item.role === 'assistant' ? '设计分析' : item.source || '会话记录'}</strong><p>{typeof item.content === 'string' ? item.content : item.text || item.message || JSON.stringify(item)}</p></article>)}</div> : <p className="st-note">描述要解决的问题。分析会结合此会话、当前候选和选中节点；建议先预览，再保存到目标方案。</p>}
    <form onSubmit={async (event) => { event.preventDefault(); const result = await converse(message); if (result) setMessage(''); }}><Field label="设计问题或调整意图"><textarea rows="3" required value={message} onChange={(event) => setMessage(event.target.value)} placeholder="例如：将通知职责拆到独立服务，并通过异步事件接收订单通知。先列出需要澄清的问题。" /></Field><div className="st-form-actions"><button className="primary-button" type="submit" disabled={busy || !message.trim() || stale}>{model.available ? '分析设计' : '生成外部分析说明'}</button><span className="st-note">仅分析与生成建议</span></div></form>
    {response ? <div className="st-analysis-result"><Tag tone={response.kind === 'proposal' ? 'target' : ''}>{({ answer: '分析结果', clarification: '待补充信息', proposal: '目标变化建议', external: '外部分析交接' })[response.kind] || response.kind}</Tag><p>{response.text}</p>{response.prompt ? <><CopyButton text={response.prompt} label="复制评审 Prompt" /><details><summary>查看完整说明</summary><pre>{response.prompt}</pre></details></> : null}{response.operations?.length ? <button type="button" className="secondary-button" disabled={busy || stale || !candidate || response.candidateId !== candidate?.id || response.candidateVersion !== candidate?.version || response.baseSnapshotId !== candidate?.baseSnapshotId} onClick={() => prepare(response.operations, response.text, response)}>预览分析建议</button> : null}</div> : null}
  </section>;
}

export function ProposalPanel({ pending, candidate, currentSnapshotId, busy, apply, discard }) {
  const stale = pending.candidateId !== candidate.id || pending.candidateVersion !== candidate.version || pending.baseSnapshotId !== currentSnapshotId;
  return <section className="st-proposal" aria-label="目标变化预览"><div className="st-section-heading"><h3>目标变化预览</h3><Tag tone="target">尚未应用</Tag></div><p>{pending.note}</p><p className="st-note">候选 v{pending.candidateVersion} · 基线 {shortId(pending.baseSnapshotId)}</p>{pending.error ? <p className="st-inline-error" role="alert">{pending.error}</p> : <><DiffSummary base={candidate.target} target={pending.preview} /><PreviewGraph model={pending.preview} /></>}<Operations operations={pending.operations} model={candidate.target} />{stale ? <p className="st-warning">预览绑定的候选或源码已变化，请重新生成预览。</p> : null}<div className="st-form-actions"><button type="button" className="primary-button" disabled={busy || stale || Boolean(pending.error)} onClick={apply}>应用到目标方案</button><button type="button" className="secondary-button" disabled={busy} onClick={discard}>放弃此预览</button></div></section>;
}

function PreviewGraph({ model }) {
  const [kind, setKind] = useState('modules'); const [scopeId, setScopeId] = useState(null); const [selectedId, setSelectedId] = useState(null);
  const view = useMemo(() => compileView(model, { kind, scopeId, limit: 80 }), [model, kind, scopeId]);
  const nodes = new Map(view.nodes.map((node) => [node.id, node])); const selected = model.nodes.find((node) => node.id === selectedId);
  return <div className="st-preview-graph"><div className="st-form-actions"><div className="st-segment">{[['modules', '模块预览'], ['dependencies', '依赖预览'], ['deployment', '部署预览']].map(([value, label]) => <button type="button" key={value} aria-pressed={kind === value} onClick={() => { setKind(value); setScopeId(null); }}>{label}</button>)}</div>{scopeId ? <button type="button" className="st-text-button" onClick={() => setScopeId(null)}>返回整个项目</button> : null}</div><div className="st-preview-canvas">{view.nodes.length ? <svg viewBox={`0 0 ${view.width} ${view.height}`} style={{ width: Math.max(500, view.width) }} role="group" aria-label="未应用的目标图预览">{view.edges.map((edge) => { const a = nodes.get(edge.from); const b = nodes.get(edge.to); return a && b ? <path key={edge.id} className="st-preview-edge" d={`M${a.x + a.width / 2},${a.y + a.height} L${b.x + b.width / 2},${b.y}`} /> : null; })}{view.nodes.map((node) => <g key={node.id} className={`st-node ${selectedId === node.id ? 'selected' : ''}`} role="button" tabIndex="0" aria-label={`预览节点：${node.label}`} onClick={() => setSelectedId(node.id)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setSelectedId(node.id); } }} onDoubleClick={() => { if (model.nodes.some((item) => item.parentId === node.id)) setScopeId(node.id); }}><rect x={node.x} y={node.y} width={node.width} height={node.height} rx="6" /><text className="st-node-kind" x={node.x + 12} y={node.y + 19}>{node.kind}</text><text className="st-node-title" x={node.x + 12} y={node.y + 41}>{node.label.slice(0, 24)}</text><title>{node.label}</title></g>)}</svg> : <p className="st-note">此视图暂无节点。</p>}</div>{selected ? <p className="st-note">{selected.label} · {selected.description || '暂无补充说明'}{selected.attributes?.responsibilities?.length ? ` · 职责：${selected.attributes.responsibilities.join('、')}` : ''}</p> : <p className="st-note">单击预览节点查看说明，双击分组下钻。此图尚未保存到候选。</p>}{view.truncated ? <p className="st-note">预览显示前 80 个节点，可双击分组缩小范围。</p> : null}</div>;
}

function OperationImport({ prepare, disabled }) {
  const [text, setText] = useState(''); const [error, setError] = useState('');
  return <form className="st-form" onSubmit={(event) => { event.preventDefault(); try { const value = JSON.parse(text); const operations = Array.isArray(value) ? value : value.operations; if (!Array.isArray(operations) || !operations.length) throw new Error('请输入非空操作数组，或包含 operations 的对象。'); prepare(operations, '外部结构化设计建议'); setError(''); } catch (failure) { setError(failure.message); } }}><Field label="外部建议 JSON"><textarea rows="6" className="st-code-input" value={text} onChange={(event) => setText(event.target.value)} placeholder='[{"type":"update-node","id":"…","changes":{"description":"…"}}]' /></Field>{error ? <p role="alert" className="st-inline-error">{error}</p> : null}<button type="submit" className="secondary-button" disabled={disabled || !text.trim()}>校验并预览导入建议</button></form>;
}

function ReviewPanel({ candidate, reviews, currentSnapshotId, command, busy }) {
  const [source, setSource] = useState(''); const [markdown, setMarkdown] = useState(''); const [opsText, setOpsText] = useState('');
  const [version, setVersion] = useState(candidate.version); const [snapshot, setSnapshot] = useState(candidate.baseSnapshotId); const [error, setError] = useState('');
  return <section className="st-reviews"><div className="st-section-heading"><h2>设计评审</h2><span>保留原文，明确选择采纳内容</span></div>
    <details><summary>导入外部评审结果</summary><form className="st-form" onSubmit={async (event) => { event.preventDefault(); try { const value = opsText.trim() ? JSON.parse(opsText) : []; const operations = Array.isArray(value) ? value : value.operations; if (!Array.isArray(operations)) throw new Error('建议操作必须为数组。'); const result = await command('import-review', { candidateId: candidate.id, candidateVersion: Number(version), baseSnapshotId: snapshot, source, markdown, operations }); if (result) { setMarkdown(''); setOpsText(''); setError(''); } } catch (failure) { setError(failure.message); } }}><Field label="评审来源"><input required placeholder="工具 / 专业评审者 / 会话链接" value={source} onChange={(event) => setSource(event.target.value)} /></Field><Field label="评审原文 Markdown"><textarea required rows="7" value={markdown} onChange={(event) => setMarkdown(event.target.value)} placeholder="结论、备选方案、影响、风险、依据、待确认项、建议变化。格式不完整也会保留原文。" /></Field><div className="st-form-grid"><Field label="评审对应候选版本"><input type="number" min="0" value={version} onChange={(event) => setVersion(event.target.value)} /></Field><Field label="评审对应源码快照"><input value={snapshot} onChange={(event) => setSnapshot(event.target.value)} /></Field></div><button type="button" className="st-text-button" onClick={() => { setVersion(candidate.version); setSnapshot(candidate.baseSnapshotId); }}>使用当前候选绑定（仅在评审确实基于此版本时）</button><details><summary>附带可采纳操作（可选 JSON）</summary><Field label="评审建议操作 JSON"><textarea rows="4" className="st-code-input" value={opsText} onChange={(event) => setOpsText(event.target.value)} /></Field></details>{error ? <p role="alert" className="st-inline-error">{error}</p> : null}<button type="submit" className="secondary-button" disabled={busy || !markdown.trim()}>保存评审原文</button></form></details>
    {!reviews.length ? <p className="st-note">暂未导入评审。先在“交接与回读”导出评审说明，将外部结果带回这里。</p> : reviews.map((review) => <ReviewCard key={review.id} review={review} candidate={candidate} currentSnapshotId={currentSnapshotId} command={command} busy={busy} />)}
  </section>;
}

function ReviewCard({ review, candidate, currentSnapshotId, command, busy }) {
  const [selected, setSelected] = useState([]); const [reason, setReason] = useState('');
  const stale = review.candidateVersion !== candidate.version || review.baseSnapshotId !== currentSnapshotId;
  const decided = review.decision !== 'pending';
  const preview = useMemo(() => {
    if (!selected.length || decided) return null;
    try { return { model: applyOperations(candidate.target, selected.map((index) => review.operations[index])) }; }
    catch (failure) { return { error: failure.message }; }
  }, [selected, decided, candidate.target, review.operations]);
  return <article className="st-review-card"><div className="st-section-heading"><h3>{review.source}</h3><Tag tone={stale ? 'attention' : ''}>{STATUS_LABELS[review.decision] || review.decision}{stale ? ' · 已过期' : ''}</Tag></div><p className="st-note">候选 v{review.candidateVersion} · 基线 {shortId(review.baseSnapshotId)}</p><pre className="st-markdown">{review.markdown}</pre>
    {review.operations.length ? <><p className="st-note">逐条选择要应用的操作。相互依赖的子集必须完整，不能自动补入未选择的建议。</p><Operations operations={review.operations} model={candidate.target} selected={selected} onSelection={!decided && !stale && !busy ? setSelected : undefined} /></> : null}
    {preview?.model ? <><DiffSummary base={candidate.target} target={preview.model} /><PreviewGraph model={preview.model} /></> : null}{preview?.error ? <p role="alert" className="st-inline-error">所选操作不能构成有效变更：{preview.error}</p> : null}
    {decided ? <div className="st-decision-reason"><p>决策理由：{review.reason}</p>{review.operations.length ? <p>已应用操作：{review.appliedOperationIndices?.map((index) => index + 1).join('、') || '无'}；未应用操作：{review.unappliedOperationIndices?.map((index) => index + 1).join('、') || '无'}</p> : null}</div> : <><Field label={`评审决策理由 · ${review.source}`}><textarea rows="2" value={reason} onChange={(event) => setReason(event.target.value)} /></Field><div className="st-form-actions"><button type="button" className="primary-button" disabled={busy || stale || !reason.trim() || Boolean(preview?.error)} onClick={() => command('decide-review', { reviewId: review.id, decision: 'accepted', reason, applyOperations: selected.length > 0, selectedOperationIndices: selected })}>{selected.length ? `采纳并应用 ${selected.length} 条操作` : '仅采纳文字意见'}</button><button type="button" className="secondary-button" disabled={busy || !reason.trim()} onClick={() => command('decide-review', { reviewId: review.id, decision: 'rejected', reason, applyOperations: false })}>驳回并记录理由</button></div></>}
  </article>;
}
